-- AlterTable
ALTER TABLE "Apartment" ADD COLUMN     "bathrooms" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "bedrooms" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN     "space" DOUBLE PRECISION NOT NULL DEFAULT 100;
